# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'temp_gui.ui'
#
# Created: Mon Jun 10 23:51:58 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from drop_window import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1040, 762)
        self.window = QtGui.QWidget(MainWindow)
        self.window.setObjectName(_fromUtf8("window"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.window)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.main = QtGui.QTabWidget(self.window)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main.sizePolicy().hasHeightForWidth())
        self.main.setSizePolicy(sizePolicy)
        self.main.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.main.setAutoFillBackground(False)
        self.main.setTabPosition(QtGui.QTabWidget.North)
        self.main.setTabShape(QtGui.QTabWidget.Rounded)
        self.main.setDocumentMode(False)
        self.main.setTabsClosable(False)
        self.main.setObjectName(_fromUtf8("main"))
        self.import_tab = QtGui.QWidget()
        self.import_tab.setObjectName(_fromUtf8("import_tab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.import_tab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.step1 = QtGui.QFrame(self.import_tab)
        self.step1.setAcceptDrops(False)
        self.step1.setAutoFillBackground(False)
        self.step1.setFrameShape(QtGui.QFrame.NoFrame)
        self.step1.setFrameShadow(QtGui.QFrame.Plain)
        self.step1.setObjectName(_fromUtf8("step1"))
        self.gridLayout_3 = QtGui.QGridLayout(self.step1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.file_display = QtGui.QLabel(self.step1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_display.sizePolicy().hasHeightForWidth())
        self.file_display.setSizePolicy(sizePolicy)
        self.file_display.setObjectName(_fromUtf8("file_display"))
        self.gridLayout_3.addWidget(self.file_display, 0, 0, 1, 1)
        self.file_input = TestListView(self.step1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_input.sizePolicy().hasHeightForWidth())
        self.gridLayout_3.addWidget(self.file_input, 2, 0, 1, 1)
        self.main_modify = QtGui.QFrame(self.step1)
        self.main_modify.setFrameShape(QtGui.QFrame.NoFrame)
        self.main_modify.setFrameShadow(QtGui.QFrame.Raised)
        self.main_modify.setLineWidth(0)
        self.main_modify.setMidLineWidth(0)
        self.main_modify.setObjectName(_fromUtf8("main_modify"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.main_modify)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.main_clear_entry = QtGui.QPushButton(self.main_modify)
        self.main_clear_entry.setObjectName(_fromUtf8("main_clear_entry"))
        self.horizontalLayout_6.addWidget(self.main_clear_entry)
        self.gridLayout_3.addWidget(self.main_modify, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.step1, 0, 0, 1, 1)
        self.step2 = QtGui.QFrame(self.import_tab)
        self.step2.setMaximumSize(QtCore.QSize(600, 16777215))
        self.step2.setFrameShape(QtGui.QFrame.NoFrame)
        self.step2.setFrameShadow(QtGui.QFrame.Plain)
        self.step2.setObjectName(_fromUtf8("step2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.step2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.step2_label = QtGui.QLabel(self.step2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step2_label.sizePolicy().hasHeightForWidth())
        self.step2_label.setSizePolicy(sizePolicy)
        self.step2_label.setScaledContents(False)
        self.step2_label.setWordWrap(False)
        self.step2_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.step2_label.setObjectName(_fromUtf8("step2_label"))
        self.gridLayout_2.addWidget(self.step2_label, 0, 0, 1, 2)
        self.plate = QtGui.QLabel(self.step2)
        self.plate.setObjectName(_fromUtf8("plate"))
        self.gridLayout_2.addWidget(self.plate, 1, 0, 1, 1)
        self.plate_entry = QtGui.QLineEdit(self.step2)
        self.plate_entry.setAcceptDrops(False)
        self.plate_entry.setObjectName(_fromUtf8("plate_entry"))
        self.gridLayout_2.addWidget(self.plate_entry, 1, 1, 1, 1)
        self.instructor = QtGui.QLabel(self.step2)
        self.instructor.setObjectName(_fromUtf8("instructor"))
        self.gridLayout_2.addWidget(self.instructor, 2, 0, 1, 1)
        self.instructor_entry = QtGui.QLineEdit(self.step2)
        self.instructor_entry.setAcceptDrops(False)
        self.instructor_entry.setObjectName(_fromUtf8("instructor_entry"))
        self.gridLayout_2.addWidget(self.instructor_entry, 2, 1, 1, 1)
        self.institution = QtGui.QLabel(self.step2)
        self.institution.setObjectName(_fromUtf8("institution"))
        self.gridLayout_2.addWidget(self.institution, 3, 0, 1, 1)
        self.institution_entry = QtGui.QLineEdit(self.step2)
        self.institution_entry.setAcceptDrops(False)
        self.institution_entry.setObjectName(_fromUtf8("institution_entry"))
        self.gridLayout_2.addWidget(self.institution_entry, 3, 1, 1, 1)
        self.gridLayout_4.addWidget(self.step2, 1, 0, 1, 1)
        self.step3 = QtGui.QFrame(self.import_tab)
        self.step3.setFrameShape(QtGui.QFrame.NoFrame)
        self.step3.setFrameShadow(QtGui.QFrame.Plain)
        self.step3.setObjectName(_fromUtf8("step3"))
        self.gridLayout = QtGui.QGridLayout(self.step3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.step3_label = QtGui.QLabel(self.step3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step3_label.sizePolicy().hasHeightForWidth())
        self.step3_label.setSizePolicy(sizePolicy)
        self.step3_label.setObjectName(_fromUtf8("step3_label"))
        self.gridLayout.addWidget(self.step3_label, 0, 0, 1, 1)
        self.frame_3 = QtGui.QFrame(self.step3)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setSpacing(2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.view_exceptions = QtGui.QPushButton(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_exceptions.sizePolicy().hasHeightForWidth())
        self.view_exceptions.setSizePolicy(sizePolicy)
        self.view_exceptions.setMinimumSize(QtCore.QSize(128, 0))
        self.view_exceptions.setObjectName(_fromUtf8("view_exceptions"))
        self.gridLayout_5.addWidget(self.view_exceptions, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 0, 3, 1, 1)
        self.main_import = QtGui.QPushButton(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_import.sizePolicy().hasHeightForWidth())
        self.main_import.setSizePolicy(sizePolicy)
        self.main_import.setMinimumSize(QtCore.QSize(128, 0))
        self.main_import.setObjectName(_fromUtf8("main_import"))
        self.gridLayout_5.addWidget(self.main_import, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.step3, 2, 0, 1, 1)
        self.main.addTab(self.import_tab, _fromUtf8(""))
        self.manual_tab = QtGui.QWidget()
        self.manual_tab.setObjectName(_fromUtf8("manual_tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.manual_tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.frame_6 = QtGui.QFrame(self.manual_tab)
        self.frame_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QtGui.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.main.addTab(self.manual_tab, _fromUtf8(""))
        self.blast_tab = QtGui.QWidget()
        self.blast_tab.setObjectName(_fromUtf8("blast_tab"))
        self.formLayout = QtGui.QFormLayout(self.blast_tab)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.blast_label = QtGui.QLabel(self.blast_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blast_label.sizePolicy().hasHeightForWidth())
        self.blast_label.setSizePolicy(sizePolicy)
        self.blast_label.setWhatsThis(_fromUtf8(""))
        self.blast_label.setTextFormat(QtCore.Qt.PlainText)
        self.blast_label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.blast_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.blast_label.setObjectName(_fromUtf8("blast_label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.blast_label)
        spacerItem4 = QtGui.QSpacerItem(0, 300, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtGui.QFormLayout.FieldRole, spacerItem4)
        spacerItem5 = QtGui.QSpacerItem(165, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.formLayout.setItem(1, QtGui.QFormLayout.LabelRole, spacerItem5)
        self.main.addTab(self.blast_tab, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.main)
        self.line = QtGui.QFrame(self.window)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_2.addWidget(self.line)
        self.log_frame = QtGui.QFrame(self.window)
        self.log_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.log_frame.setFrameShadow(QtGui.QFrame.Plain)
        self.log_frame.setObjectName(_fromUtf8("log_frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.log_frame)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.log_label = QtGui.QLabel(self.log_frame)
        self.log_label.setObjectName(_fromUtf8("log_label"))
        self.verticalLayout_2.addWidget(self.log_label)
        self.log = QtGui.QTextBrowser(self.log_frame)
        self.log.setAcceptDrops(False)
        self.log.setAutoFillBackground(False)
        self.log.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.log.setOverwriteMode(False)
        self.log.setOpenLinks(False)
        self.log.setObjectName(_fromUtf8("log"))
        self.verticalLayout_2.addWidget(self.log)
        self.frame_2 = QtGui.QFrame(self.log_frame)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.view_log = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_log.sizePolicy().hasHeightForWidth())
        self.view_log.setSizePolicy(sizePolicy)
        self.view_log.setMinimumSize(QtCore.QSize(128, 0))
        self.view_log.setObjectName(_fromUtf8("view_log"))
        self.horizontalLayout.addWidget(self.view_log)
        self.close = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close.sizePolicy().hasHeightForWidth())
        self.close.setSizePolicy(sizePolicy)
        self.close.setMinimumSize(QtCore.QSize(128, 0))
        self.close.setObjectName(_fromUtf8("close"))
        self.horizontalLayout.addWidget(self.close)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.horizontalLayout_2.addWidget(self.log_frame)
        MainWindow.setCentralWidget(self.window)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.statusbar.setStatusTip(_fromUtf8(""))
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.main.setCurrentIndex(1)
        QtCore.QObject.connect(self.close, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.file_display.setText(_translate("MainWindow", "Step 1: Drag sequence files here.", None))
        self.main_clear_entry.setToolTip(_translate("MainWindow", "Clear entry list", None))
        self.main_clear_entry.setText(_translate("MainWindow", "Clear", None))
        self.step2_label.setText(_translate("MainWindow", "Step 2: Input information for the files", None))
        self.plate.setText(_translate("MainWindow", "Plate", None))
        self.plate_entry.setWhatsThis(_translate("MainWindow", "Plate name", None))
        self.plate_entry.setPlaceholderText(_translate("MainWindow", "(ex: 3)", None))
        self.instructor.setText(_translate("MainWindow", "Instructor", None))
        self.instructor_entry.setPlaceholderText(_translate("MainWindow", "(ex: Bangera)", None))
        self.institution.setText(_translate("MainWindow", "Institution", None))
        self.institution_entry.setPlaceholderText(_translate("MainWindow", "(ex: Bellevue College)", None))
        self.step3_label.setText(_translate("MainWindow", "Step 3: Import the files", None))
        self.view_exceptions.setText(_translate("MainWindow", "Exceptions", None))
        self.main_import.setText(_translate("MainWindow", "Import", None))
        self.main.setTabText(self.main.indexOf(self.import_tab), _translate("MainWindow", "Standard Input", None))
        self.label.setText(_translate("MainWindow", "Unfinished!!!", None))
        self.main.setTabText(self.main.indexOf(self.manual_tab), _translate("MainWindow", "Manual Input", None))
        self.blast_label.setText(_translate("MainWindow", "To be implemented", None))
        self.main.setTabText(self.main.indexOf(self.blast_tab), _translate("MainWindow", "BLAST search", None))
        self.log_label.setText(_translate("MainWindow", "Transaction Log:", None))
        self.log.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Open Sans\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Cantarell\';\"><br /></p></body></html>", None))
        self.view_log.setText(_translate("MainWindow", "Open log file", None))
        self.close.setText(_translate("MainWindow", "Close", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

